### ISSUE TITLE
Feature suggestion for calender widget

### ISSUE THREAD

**Issue by MajorTomDE** [rudotriton/scriptable-calendar-widget#14]
Hey,

it would be great, If calendar widget will be configurable in this way:

![107887147-4306bf00-6f04-11eb-8045-a9a0f2c3bfa8](https://user-images.githubusercontent.com/76742790/110127970-8b5c2300-7dc6-11eb-9c00-afbd1061cd90.jpeg)

I'm looking for an solution who only display all upcoming events as a list.
Unfortunately, the Agenda+ app has been removed from the App Store.

Thank you
Thomas

**Comment by iHarshad** [comment]
Here is an intermediate solution.

1.  Comment out the below-mentioned lines
<details>
  <summary>src/buildLargeWidget.ts </summary>

```diff
diff --git a/src/buildLargeWidget.ts b/src/buildLargeWidget.ts
index 3e2865c..9757a2c 100644
--- a/src/buildLargeWidget.ts
+++ b/src/buildLargeWidget.ts
@@ -1,4 +1,4 @@
-1  :import buildCalendarView from "./buildCalendarView";
+  1:// import buildCalendarView from "./buildCalendarView";
 2 2:import buildEventsView from "./buildEventsView";
 3 3:import { Settings } from "./settings";
 4 4:
@@ -25,7 +25,7 @@ async function buildLargeWidget(
 25 25:    eventLimit: 8,
 26 26:    eventSpacer: 6,
 27 27:  });
-28  :  await buildCalendarView(date, rightSide, settings);
+  28:  // await buildCalendarView(date, rightSide, settings);
 29 29:  // add space between the calendar and any events below it
 30 30:  rightSide.addSpacer();
 31 31:  await buildEventsView(rightSideEvents, rightSide, settings, {
```
</details>


<details>
<summary>src/buildWidget.ts</summary>

```diff
diff --git a/src/buildWidget.ts b/src/buildWidget.ts
index 2a0f8e0..b5b651f 100644
--- a/src/buildWidget.ts
+++ b/src/buildWidget.ts
@@ -30,12 +30,12 @@ async function buildWidget(settings: Settings): Promise<ListWidget> {
 30 30:      break;
 31 31:    default:
 32 32:      if (settings.flipped) {
-33   :        await buildCalendarView(today, globalStack, settings);
+   33:        // await buildCalendarView(today, globalStack, settings);
 34 34:        globalStack.addSpacer(10);
 35 35:        await buildEventsView(events, globalStack, settings);
 36 36:      } else {
 37 37:        await buildEventsView(events, globalStack, settings);
-38   :        await buildCalendarView(today, globalStack, settings);
+   38:        // await buildCalendarView(today, globalStack, settings);
 39 39:      }
 40 40:      break;
 41 41:  }
```

</details>

2. Build the project with `rpm run build`

3. Update the iOS Scriptable widget code with the newly generated `calendar.js` file

Small & Medium        |  Large
:-------------------------:|:-------------------------:
![Medium-2](https://user-images.githubusercontent.com/8861290/225847274-9bcb52ed-f81f-4e15-9331-1b9e5e07a1d0.jpeg)  |  ![Large](https://user-images.githubusercontent.com/8861290/225847184-f410d4ce-66d7-43e2-a5d9-243efae110ff.jpeg)
