### ISSUE TITLE
Date and day is off instead of the 17 on Wednesday it show the 17 on Tuesday and so on and on. How can I fix this? thank you

### ISSUE THREAD

**Issue by mtoutkast** [rudotriton/scriptable-calendar-widget#15]

**Comment by rudotriton** [comment]
Are you using the current version of the script and what settings have you changed? There was a similar issue back in November, but the current script should show it correctly when the week is set to start on a Monday as well as on a Sunday.

<p align="center" >
    <img width="450" alt="scriptable calendar" src ="https://user-images.githubusercontent.com/14181026/111511902-d75c7f80-8757-11eb-9186-4cc94f466d37.png">
</p>

**Comment by mtoutkast** [comment]
Thank you for the quick response I haven't changed anything I think is perfect but I'm not sure which version I'm running really?

**Comment by rudotriton** [comment]
If you copied the contents of the [calendar.js](https://github.com/rudotriton/scriptable-calendar-widget/blob/main/calendar.js) file then it's up to date and I'm at a loss what could cause this, because I'd expect that they then wouldn't line up for me either.

**Comment by starfuz** [comment]
I’m having this issue as well! I just copied the code and ran it without changing anything and this is happening. I’ve tried on two different phones as well and it’s still happening
