### ISSUE TITLE
Font Size

### ISSUE THREAD

**Issue by Themivoc** [rudotriton/scriptable-calendar-widget#2]
Hey, first thanks for the great widget!
Talking about the event view, do you know an option to make the text font bold or to increase the font size?

**Comment by rudotriton** [comment]
https://github.com/rudotriton/scriptable-calendar-widget/blob/d36eb7d7aa51739248ea0271f3556e44544aba88/calendar.js#L407

The event's title is specified in `formatEvent()` where the font is set as size 14 medium system font. You can change the number to change its size or swap the font itself for something different. The [docs](https://docs.scriptable.app/font/) offer more font options, but for bold it would be `Font.boldSystemFont(14)`.

**Comment by Themivoc** [comment]
Perfect, thank you!
Do you also happen to know how I can change the text alignment to always start from top?
Currently it is always centered in the middle of the widget.

**Comment by rudotriton** [comment]
You can remove or comment the following line. If you think that the text is then close to the upper edge, you can change that spacer to a fixed size one, e.g. `leftStack.addSpacer(8);` or whatever size you think is suitable.

https://github.com/rudotriton/scriptable-calendar-widget/blob/d36eb7d7aa51739248ea0271f3556e44544aba88/calendar.js#L86-L86
