### ISSUE TITLE
showCompleteTitle doesn’t work

### ISSUE THREAD

**Issue by ghost** [rudotriton/scriptable-calendar-widget#24]
The variable showCompleteTitle doesn’t seem to work; event titles will still be truncated whether it’s set to true or false. To see the full event title, is there a way to increase the line limit? Would that fix this issue?

**Comment by rudotriton** [comment]
I have thought about this a bit now. On a medium/small widget it fits 3 events. If there are only 2 events to show, then there is some leftover space, so one of the titles can span 2 lines (even though there seems to be space for more lines, for some reason it can't fit more than that). It's not a super helpful setting for that reason. However, on a large widget, there is likely more unused space, especially when limiting the events to the current day, so in such a case it would take effect more often.
