### ISSUE TITLE
Wishings for a large widget

### ISSUE THREAD

**Issue by sleepyhellow** [rudotriton/scriptable-calendar-widget#4]
Hello  rudotriton,

thanks a lot for this widget. I like it very mutch. 

Would it be possible to have a large widget with these options:
- View events for the next 7 or better 10 days (to see events at the next week).
- Show the events left and under the month view in 2 columns.
- Show the day over the event.
- Seperate the days with a line.
- Have a grey bar over the days to see them better.

I think at the picture you can see good what I mean.

![Kalender (2)](https://user-images.githubusercontent.com/74114869/98499318-75d85180-2249-11eb-8f30-8c9b02dc7cd0.jpg)

What do you think? Can you make my wish comes true? ;-)

**Comment by thomaskeim** [comment]
Any news about this request? I'm looking for exact the same widget design :-)
Also it should be possible to only show events from calendars who are enabled in the calendar app.
