### ISSUE TITLE
Open Fantastical instead of native Calendar app

### ISSUE THREAD

**Issue by ericfledderman** [rudotriton/scriptable-calendar-widget#6]
Would it be possible to modify the codebase (or the readme) to offer/instruct a user how to have the widget open Fantastical instead of the native Calendar app?

**Comment by rudotriton** [comment]
I have written something about this in the readme now, but what you are looking for is:

https://github.com/rudotriton/scriptable-calendar-widget/blob/9dea39563d6ad983fdad3d8c4ac94f3f04273bf5/calendar.js#L52

Changing it to...

```diff
- const appleDate = new Date("2001/01/01");
- const timestamp = (new Date().getTime() - appleDate.getTime()) / 1000;
- const callback = new CallbackURL("calshow:" + timestamp);
+ const callback = new CallbackURL("x-fantastical3://");
+ callback.addParameter("date", "today");
```

...should do it.

I'm not a Fantastical user so I can't actually test it, but this is what their [documentation](https://flexibits.com/fantastical-ios/help/integration) would suggest. It is possible that the `addParameter` line is not needed and the app opens some desired view by default, or that `today` won't work and it needs a `yyyy-mm-dd` kind of date. However, they say that natural language works.

**Comment by ericfledderman** [comment]
Awesome.  I’ll test it for and update you before I close this out.

Much appreciated.

**Comment by ericfledderman** [comment]
This has now but tested and confirmed.

Thanks again.

**Comment by rtk170** [comment]
Is it possible to set this so that clicking on a date in the calendar view will open Fantastical (or the iOS Calendar App) at that specific date? Currently it will open the app at todays date
