### ISSUE TITLE
I want to widen the gap between calender and event. 

### ISSUE THREAD

**Issue by ohhyemee** [rudotriton/scriptable-calendar-widget#9]
I want to widen the gap between calender and event. Please tell me which part to modify and the number to enter. There are two types of users: iPhone 12 mini and 12promax. I like your calendar because the color is pretty and the size is very constant.

**Comment by rudotriton** [comment]
The gap between the events and the calendar is set to auto, meaning that it is as wide as possible. The left and right padding have a fixed size and the calendar has a fixed size, so all the space left over, is allocated to the events. If the widget background blends in with your wallpaper, then you can create an illusion of a wider gap, by removing the padding on either side.

It is set to a padding of 16 on each side:

https://github.com/rudotriton/scriptable-calendar-widget/blob/86b9b4086b65503d237c4d1f234e16602a1917c9/calendar.js#L61

<p align="center" >
    <img width="350" alt="scriptable calendar" src ="https://user-images.githubusercontent.com/14181026/103169387-cdf00500-4843-11eb-834c-dea13514943c.png">
</p>

It is `(top, right, bottom, left)` so `(16, 0, 16, 0)` gets rid of it on the sides.

<p align="center" >
    <img width="350" alt="scriptable calendar" src ="https://user-images.githubusercontent.com/14181026/103169376-b284fa00-4843-11eb-9d40-efbf2921fe26.png">
</p>

I'm not sure if this solves your problem.
